repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.5.1
    hooks:
    - id: pyupgrade
      args: [--py36-plus]
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
