dist: xenial   # required for Python >= 3.7

sudo: required

language: python

services:
  - docker

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - POSTGRES_DB=comic
    - POSTGRES_HOST=127.0.0.1
    - POSTGRES_PASSWORD=comic
    - POSTGRES_USER=comic
    - POSTGRES_PORT=5432

jobs:
  include:
    - &test
      stage: test
      if: branch = master AND type = pull_request
      language: python
      python: "3.6"
      before_install:
        - sudo service postgresql stop
        - docker run -d -p $POSTGRES_PORT:5432 -e POSTGRES_DB=$POSTGRES_DB -e POSTGRES_USER=$POSTGRES_USER -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD postgres:10.4
        - sudo mkdir -p /tmp/coverage
        - sudo chmod a+w /tmp/coverage

      install:
        - pip install -r requirements.txt
        - pip install -r requirements.dev.txt

      before_script:
        - |
          RETRIES=10
          until pg_isready --host=$POSTGRES_HOST --port=$POSTGRES_PORT --username=$POSTGRES_USER --timeout=1 || [ $RETRIES -eq 0 ]; do
              RETRIES=$((RETRIES-1))
              sleep 1
          done

      script:
        - pytest --cov=app/comic --cov-report=xml app

    - <<: *test
      python: "3.7"
      after_script:
        - sonar-scanner

    - stage: deploy
      if: branch = master AND type = push
      before_install: skip
      install: skip
      before_script: skip
      script: docker build . -t eyra/comic:latest -t eyra/comic:$TRAVIS_BUILD_NUMBER
      after_success: bash -c "docker login -u eyrabenchmark1 -p $DOCKER_PASSWORD && docker push eyra/comic:$TRAVIS_BUILD_NUMBER && docker push eyra/comic:latest"

addons:
  sonarcloud:
    organization: "eyra-benchmark"
    token:
      secure: "XgcSnZ+Kk+Zhs2Wx9D/z6OaE7ZO6mPpPEk1IgROjaowK0rNFQ0n5l1wgkGNGwhPpycpy23CwRV5surXZu5yjAcF6sal/BX27san117DUKpxLrvPGiYK/1pdiLckKB/s1/PnoRHlqNGhV0dcswOuj0F5qLGdibYX6nk6g5ZOI7qKSW8aVpa6/flLKDCsfmxvfgAZ9/aXGPKECig+fxPG2csIFOsohTIc/y3Ry9k2GnTEYoH7D3/6ILkfjgBA5Z1Z30h1TcJ3pWMKAnsdoFJ9UUj+06XdVzQESvgV0Fr4eKm0VHk/cb6ON5btcpub5rm/6mH/9rggw6jAgFTHoGPiAdbopetPTBk2NhNSpnqOLA2Jg/E6+ls7cI5MJT4N1c0o2L/qTOzxeG4WiUKMVT8kAi2rmFTfNijWkmrUu0yFxYVUA+KksCrzzfMrUd54YICW1mZBtgO5KBxH2nlEi0Deuw3laksccEmxIVo0XnFn1mjhvrzttOMwlw3TTBK2w8secWz0Upy87qPHfYp8uig4Vna0bEiSD+jWalCMPHr0QRrF8MbElJQ+JSsmsx7WgbJx+eTMVJ0lxs7N6CYcTAgImcXo5sM4chQ8cOAxCLpzFMR/mY9p/vc9Y627/lxuvRIE2g/Af4qm8S5Tu/QnTYe3E8U1RyJSDKfs9VkWy/7noaP8="

git:
  depth: false