
name: Automate issues and PRs to RSE project

on: [issues, pull_request]

jobs:
  add-new-issues-to-project:
    runs-on: ubuntu-latest
    steps:
    - name: Add new issues to RSE To do
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'issues' && github.event.action == 'opened'
      env:
        GITHUB_TOKEN: ${{ secrets.GRAND_CHALLENGE_PROJECT_KEY }}
        GITHUB_PROJECT_URL: https://github.com/orgs/comic/projects/1
        GITHUB_PROJECT_COLUMN_NAME: To do
    - name: Add new PRs to RSE Review in progress
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      env:
        GITHUB_TOKEN: ${{ secrets.GRAND_CHALLENGE_PROJECT_KEY }}
        GITHUB_PROJECT_URL: https://github.com/orgs/comic/projects/1
        GITHUB_PROJECT_COLUMN_NAME: Review in progress
